name: test-ubsan

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  ubsan:
    name: ubsan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup vcpkg
        run: |
          mkdir local_vcpkg_installation
          cmake --version
          cd local_vcpkg_installation
          git init
          git remote add origin "https://github.com/microsoft/vcpkg.git"
          git fetch origin 84bab45d415d22042bd0b9081aea57f362da3f35
          git checkout 84bab45d415d22042bd0b9081aea57f362da3f35
          ./bootstrap-vcpkg.sh
          echo "VCPKG_ROOT=${{ github.workspace }}/local_vcpkg_installation" >> $GITHUB_ENV
          echo "VCPKG_TOOLCHAIN_PATH=${{ github.workspace }}/local_vcpkg_installation/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV
          echo "${{ github.workspace }}/local_vcpkg_installation" >> $GITHUB_PATH

      - name: Configure
        run: make configure

      - name: UBSan
        run: make ubsan
